/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationView: typeof import('./src/components/application-view.vue')['default']
    AppSettings: typeof import('./src/components/app-settings.vue')['default']
    ContactIcon: typeof import('./src/components/contact-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
